def loop():
    print('------------------------------')
    print(' Hello! I\'m AI-game!')
    print(' Good to see u in my programme:)')
    print('------------------------------')
    print(' Decordis has done the game:')
    print(' Rock-paper-Scissors')
    print('------------------------------')
    print('  So, let\'s play!')
    print('!'*13,'MAIN','!'*13, sep='')
    print('  I use ONLY numbers:')
    print(' 1 - Scissors\n 2 - Stone \n 3 - Paper')
